### ISSUE TITLE
How should Miro records that don't have an <image_title> field be handled?

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform-api#356]
From CloudWatch:

```
INFO u.a.w.transformer.parsers.MiroParser - Parsed DynamoDB record MiroTransformable(V0000218EB,Images-V,{"image_no_calc":"V0000218EB","image_int_default":null,"image_wellcome_pub_date":null,"image_wellcome_pub_date_from":null,"image_wellcome_pub_date_to":null,"image_wellcome_publications":null,"image_lcsh_place":null,"image_copyright_info":null,"image_dup_...
[ForkJoinPool-2-worker-77] ERROR u.a.w.t.receive.RecordReceiver - Failed to perform transform to unified item
java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:347)
    at scala.None$.get(Option.scala:345)
    at uk.ac.wellcome.models.MiroTransformable$$anonfun$transform$1.apply(MiroTransformable.scala:40)
    at uk.ac.wellcome.models.MiroTransformable$$anonfun$transform$1.apply(MiroTransformable.scala:32)
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
    at scala.util.Try$.apply(Try.scala:192)
    at scala.util.Success.map(Try.scala:237)
    at uk.ac.wellcome.models.MiroTransformable.transform(MiroTransformable.scala:32)
    at uk.ac.wellcome.transformer.receive.RecordReceiver.transformDynamoRecord(RecordReceiver.scala:52)
    at uk.ac.wellcome.transformer.receive.RecordReceiver$$anonfun$receiveRecord$2$$anonfun$1$$anonfun$apply$1.apply(RecordReceiver.scala:31)
    at uk.ac.wellcome.transformer.receive.RecordReceiver$$anonfun$receiveRecord$2$$anonfun$1$$anonfun$apply$1.apply(RecordReceiver.scala:29)
    at scala.util.Success.flatMap(Try.scala:231)
    at uk.ac.wellcome.transformer.receive.RecordReceiver$$anonfun$receiveRecord$2$$anonfun$1.apply(RecordReceiver.scala:29)
    at uk.ac.wellcome.transformer.receive.RecordReceiver$$anonfun$receiveRecord$2$$anonfun$1.apply(RecordReceiver.scala:28)
    at scala.util.Success.flatMap(Try.scala:231)
    at uk.ac.wellcome.transformer.receive.RecordReceiver$$anonfun$receiveRecord$2.apply(RecordReceiver.scala:28)
    at uk.ac.wellcome.transformer.receive.RecordReceiver$$anonfun$receiveRecord$2.apply(RecordReceiver.scala:26)
    at uk.ac.wellcome.metrics.MetricsSender$$anonfun$1.apply(MetricsSender.scala:21)
    at uk.ac.wellcome.metrics.MetricsSender$$anonfun$1.apply(MetricsSender.scala:21)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
    at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by alexwlchan** [comment]
Similar tracebacks on V0000233FB, V0000246EL, V0000246ER, V0000274EB, V0000274FB, V0000283EB.

**Comment by alexwlchan** [comment]
Related to #308 – these are all items leaking from the pipeline.

**Comment by alexwlchan** [comment]
This is the line where it's breaking:

```scala
// <image_title>: the Short Description.  This maps to our property
// "label".
val label = miroData.title.get
```

And indeed, inspecting these records in the XML backups, the `<image_title>` field is empty for each of them. I’ll punt to @ChristopherHilton/@jtweed for suggestions about which field to use in lieu (or if we should just put an empty label on these records).

**Comment by jtweed** [comment]
These images don't have titles as they haven't been catalogued. I've checked and we should not ingest them.

The two elements to check in the XML are:

- `<all_draft>` should be set to `N`
- `<image_copyright_cleared>` should be set to `Y`
